### ISSUE TITLE
make the ghcr packages publicly visible

### ISSUE THREAD

**Issue by exaexa** [ResearchLuxembourg/CovidReproductionNumber.jl#7]
docker containers are built here:
https://github.com/ResearchLuxembourg/CovidReproductionNumber.jl/pkgs/container/covid-reproduction-number
unfortunately the packages are private right now.

@laurentheirendt can you please click the package visibility settings somewhere in organization config? AFAIK it was named like "publishable packages" around here: https://github.com/orgs/ResearchLuxembourg/packages

I can't change the visibility because:
![image](https://user-images.githubusercontent.com/271543/174433597-459c8120-7015-4914-9443-76268287c592.png)

**Comment by laurentheirendt** [comment]
done ✅
